const POSTS = 'posts/setPosts'
const FETCH_INITIAL_DATA_SUCCESS = 'FETCH_INITIAL_DATA_SUCCESS'
const FETCH_INITIAL_DATA_REQUEST = 'FETCH_INITIAL_DATA_REQUEST'
const FETCH_INITIAL_DATA_ERROR = 'FETCH_INITIAL_DATA_ERROR'

const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR'

const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

const SEARCH_VALUE = 'SEARCH_VALUE'
const FETCH_ERROR = 'FETCH_ERROR'

export {
    POSTS, 
    FETCH_INITIAL_DATA_SUCCESS, 
    FETCH_INITIAL_DATA_REQUEST, 
    FETCH_INITIAL_DATA_ERROR, 
    FETCH_ERROR, 
    FETCH_COMMENTS_SUCCESS,
    FETCH_COMMENTS_REQUEST,
    FETCH_COMMENTS_ERROR,
    FETCH_POSTS_SUCCESS,
    FETCH_POSTS_REQUEST,
    FETCH_POSTS_ERROR,
    FETCH_USERS_SUCCESS,
    FETCH_USERS_REQUEST,
    FETCH_USERS_ERROR,
    SEARCH_VALUE
}